### ISSUE TITLE
[Rilis] Versi 2.1.0

### ISSUE THREAD

**Issue by noaione** [noaione/naoTimes#29]
Ini merupakan issue untuk tracking proses versi 2.1.0, semua fitur yang akan direncanakan ditambah di versi ini akan ditandai di sini.

Fitur Baru:
- [x] Kalkulator (#26)
- [x] WolframAlpha (#27)
- [x] Tesaurus (#25)
- [x] Giveaway command (#20)
- [x] Image Booru (#17)
- [x] Jisho dan Kanji (#13, #14, #15, #16)
- [x] VTuber (#13, #14)

Enhancements:
- [x] Migrasi ke Redis untuk local data. (#12)
- [x] Percantik progress Showtimes (#25)
- [x] Otomatis tambah role ke staff pas tambahutang (#23)
- [x] Buat parser untuk waktu dengan custom format custom (30d, 30h, 30m, etc.) (#20)
- [x] Paginator (#12)
- [x] Buat presences menjadi cogs sendiri dan buat lebih scalable. (#36)
- [x] Percantik Schema Showtimes (Tracking: #37)

General "Fixes":
- [x] Perbaiki masalah staff tidak bisa menandakan progress walaupun ada role dan posisi staff (#25)
- [x] Perbaiki masalah tidak ada annunce channel (#12)
- [x] Prefix tidak tereset kadang (#17)

Finalisasi:
- [ ] Atur Dokumentasi (#28)
- [ ] Bump version

Fitur baru akan di rollup menjadi PR besar.
Develoopment terjadi di Repository private dan akan di sync dengan repo utama jika fitur sudah dianggap siap.

**Comment by noaione** [comment]
Hampir seluruh perintah yang ditambahkan telah dirilis di bot, closing.
