### ISSUE TITLE
[Cogs/Schema] Showtimes

### ISSUE THREAD

**Issue by noaione** [noaione/naoTimes#37]
Schema database untuk Showtimes itu ampas, jadi mari kita buat ulang schemanya dan sekaligus perbaiki beberapa problem pada cogs Showtimes.

## TO-DO
- [x] Masukan Showtimes ke mode Maintenance
- [x] Migrasi Schema
- [x] Atur bridge database
- [ ] Atur cogs
	- [x] Base helper `[Priority: High]`
	- [x] User (~~tagih~~, ~~jadwal~~, ~~staff~~) `[Priority: High]`
	- [x] Staff (~~beres~~, ~~gakjadi~~, ~~tandakan~~, ~~rilis~~, ~~batalrilis~~) `[Priority: High]`
	- [x] Admin (~~tambahutang~~, ~~ubahdata~~) `[Priority: Medium]`
	- [x] FansubDB `[Priority: Low]`
	- [ ] Owner (tambah, hapus, tambahadmin, hapusadmin, fetchdb, patchdb, etc.) `[Priority: Low]`
	- [x] Lain-lain (~~alias~~, ~~kolaborasi~~) `[Priority: Medium]`
- [x] ShowUI Login stuff
- [x] naoTimesUI Socket parity
- [x] Atur Redis-parity

## Additional Tasks
- [ ] Jangan list role kalo misalkan staff yg keisi unknown. `[Priority: Low]`

## To be fixed
- [x] Mekanisme lock untuk Queue

Jika Cogs sudah dicentang, artinya sudah bisa dipakai lagi.

Langkah selanjutnya setelah ini adalah ngerjain https://github.com/naoTimesdev/webpanel

Relevan #29

**Comment by noaione** [comment]
Welp, command user dan staff sudah bisa diakses kembali. Yang lain tetap disabled sampai beres.
PR auto-sync akan dibuat kalo misalkan dah beres semuanya.

**Comment by noaione** [comment]
Command Admin dan Lain-lain done, kalo ada masalah bisa langsung lapor di sini.

**Comment by noaione** [comment]
FSDB done, sisa owner. Cogs sudah bisa dipake lagi.
PR akan dirilis setelah Cogs owner done.
