### ISSUE TITLE
[Rilis] Versi 3.0.0

### ISSUE THREAD

**Issue by noaione** [noaione/naoTimes#57]
Ya, situ baca dengan benar. naoTimes akan mendapatkan versi 3.0.0.
Dikarenakan rewrite yang sedang saya lakukan di repository development, saya akan menaikan versi bot dari v2.x ke v3.x

**Pengumuman**
Minimal Python untuk bot naoTimes sekarang dinaikan dari Python 3.6 ke Python 3.8 dengan rekomendasi Python 3.9

## Quality-of-life changes
- [x] Full rewrite bot, lebih dynamic dari sebelumnya
- [x] Menggunakan Model untuk rata-rata data, harusnya lebih stabil dan jarang error.
- [x] Sistem "Socket server" yang lebih bagus, ini dapat diexpand dikarenakan menggunakan satu port dan anda dapat binding untuk event tertentu.
- [x] Fully-typed, ini yang makan waktu paling banyak
- [x] Converters untuk berbagai macam hal
- [x] Custom context, ini ngebantu untuk beberapa fitur yang tak gunain.
- [x] Pindah ke v2 discord.py/~~nextcord~~/~~pycord~~/naoTimes fork (ndiscord.py)
- [x] ~~Pindah dari discord.py ke nextcord~~ (#55)
- [x] ~~Pindah dari discord-py-slash-command ke dislash.py~~ (#56)
- [x] ~~Pindah dari discord.py dan discord-py-slash-command ke pycord~~ (#58)
- [x] Pindah ke ndiscord.py (https://github.com/naoTimesdev/ndiscord.py)
- ~~Gunakan Sharding ([`AutoShardedClient`](https://ndiscordpy.readthedocs.io/en/latest/api.html#autoshardedclient) atau [`AutoShardedBot`](https://ndiscordpy.readthedocs.io/en/latest/ext/commands/api.html#autoshardedbot))~~ Will not be used yet.

## Fitur baru
- [x] Sistem modlog dan moderasi yang lebih bagus
- [x] Sistem interaksi via Discord View/UI (Pagination)
- [x] Mencari padanan kata luar negeri
- [x] Translasi
- [x] User Info Card (Sekarang merupakan gambar) (#51, #53)
- [x] Definisi kata bahasa inggris dan tesaurusnya (#49)
- [x] Custom reaction, bot akan menjawab sebuah reaksi dari user jika menemukan yang cocok (#47)
- [ ] #44 

## Perbaikan
- [x] Sistem voting sekarang harusnya sudah benar.
- [x] Showtimes harusnya mulai jarang error lagi.
- [ ] Help command mk.2
- [x] Support untuk Python 3.9

## Testing
__**Jika ada yang ingin membantu, mohon kontak saya di Discord: N4O#8868**__

- [x] Weebs
	- [x] Animanga
	- [x] Visual Novel
	- [x] VTuber
- [x] R-18
	- [x] NH
	- [x] Booru
- [x] Fun
	- [x] Reaksi Kustom
	- [x] RNG related (dadu, pilih, dsb)
	- [x] Tanya pertanyaan ke Bot
	- [x] Informasi Peladen
	- [x] Informasi User
- [x] Kutubuku
	- [x] Jisho
	- [x] Kateglo (Antonim/Sinonim)
	- [x] KBBI
	- [x] Padanan kata
	- [x] Tesaurus
	- [x] Webster (Dictionary + Thesaurus English)
		- [x] Fix linking
	- [x] WolframAlpha
	- [x] Kalkulator
	- [x] Translasi (MTL/GTL) [Also fixed the URL format]
- [x] Moderasi
	- [x] Logging
		- [x] Channel
		- [x] Member
		- [x] Message
		- [x] Thread
	- [x] Automoderator
	- [x] Moderasi kanal
	- [x] Moderasi peladen
	- [x] Moderasi member
	- [x] Moderasi pesan
	- [x] Moderasi thread
- [x] Peninjau (Scrapper)
	- [x] Anibin
	- [x] Cuaca
	- [x] Kurs Mata Uang
	- [x] Saus gambar (SauceNAO, IQDB)
	- [x] Gaming
		- [x] Steam
		- [x] How Long To Beat (HLTB)
		- [x] Steam Status
- [x] Showtimes
	- [x] Admin (Tambah/Ubah)
	- [x] Alias
	- [x] FansubRSS
	- [x] Integrasi FansubDB
	- [x] Kolaborasi
	- [x] Integrasi WebUI
	- [x] Staff
	- [x] User/Member
- [x] Voting
	- [x] Vote normal
	- [x] Single vote choice
	- [x] Vote kick/ban
- [ ] Meta
	- [x] Prefix
	- [x] Presensi
	- [x] Ticket System
	- [x] Error Logging
	- [ ] Help
	- [x] More Meta Stuff
- [ ] Bot Owner
	- [x] Premium giving
	- [ ] Module hot-reloading
	- [ ] ????

## Finalisasi
- [ ] Buat release note
- [ ] Buat blog post
- [ ] Finalisasi dokumentasi di Website
- [ ] Publish

Fitur baru akan di rollup menjadi PR besar.
Development terjadi di Repository private dan akan di sync dengan repo utama jika fitur sudah dianggap siap.

**Update**
Versi 3.0 dapat diliat di sini: https://github.com/naoTimesdev/naoTimes/tree/v3-rewrite
Branch tersebut akan diupdate manual jika saya ingat.

**Comment by noaione** [comment]
Statistik PR v3 di development repo. (2021-09-05 00:10 WIB)

![Screenshot_20210905-011151_GitHub.jpg](https://user-images.githubusercontent.com/34302902/132102905-891be1ea-7ac6-437c-b052-3c2af02cd2e8.jpg)

**Comment by noaione** [comment]
Perubahan: naoTimes membutuhkan versi Python 3.8+
Python 3.7 kebawah saya drop supportnya.

**Comment by noaione** [comment]
Nextcord+dislash.py diubah ke pycord versi fork naoTimes.

https://github.com/naoTimesdev/pycord

**Comment by noaione** [comment]
Pycord diubah menjadi fork naoTimes

https://github.com/naoTimesdev/ndiscord.py

**Comment by noaione** [comment]
v3 dapat diliat di sini: https://github.com/naoTimesdev/naoTimes/tree/v3-rewrite
Masih dalam pengerjaan dikarenakan beberapa fitur masih belum selesai!
